services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: sumni-finance-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-sumni_finance}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sumni
    labels:
      app: "finance-database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user}"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M

  backend:
    image: ghcr.io/quangbach27/sumni-finance-backend:${BACKEND_IMAGE_TAG:-latest}
    container_name: sumni-finance-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_URL=${POSTGRES_URL:-postgres://user:password@db:5432/sumni_finance}
      - BANK_LOOKUP_BASE_URL=https://api.vietqr.io
      - APP_ENV=${APP_ENV:-staging}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
    labels:
      app: "finance-backend"
    networks:
      - sumni
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M

  frontend:
    image: ghcr.io/quangbach27/sumni-finance-frontend-vite:${FRONTEND_IMAGE_TAG:-latest}
    container_name: sumni-finance-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BACKEND=${VITE_API_BACKEND:-https://api.deadun.site}
    networks:
      - sumni
    labels:
      app: "finance-frontend"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 64M
  
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    environment:
      - LOKI_URL=${LOKI_URL}
      - LOKI_USERNAME=${LOKI_USERNAME}
      - LOKI_PASSWORD=${LOKI_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./grafana/alloy-config.alloy:/etc/alloy/config.alloy
    command: >
      run
      --server.http.listen-addr=0.0.0.0:12345
      /etc/alloy/config.alloy
    restart: unless-stopped
    ports:
    - "12345:12345"
    networks:
    - sumni 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
        reservations:
          cpus: "0.05"
          memory: 64M


networks:
  sumni:
    driver: bridge

volumes:
  pg_data:
